### ISSUE TITLE
Printing throws an error

### ISSUE THREAD

**Issue by laingsimon** [laingsimon/preview-dot#4]
1. Preview an image
1. Right click and click print
1. An error message is presented, appears to be related to getting the source of the image.

May require the image be saved to disk first?
May require a re-translate of the graph to have at a higher resolution for print

**Comment by laingsimon** [comment]
Blocks #7

**Comment by laingsimon** [comment]
```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at PreviewDot.PreviewControl.itmPrint_Click(Object sender, EventArgs e) in D:\Simon\Development\preview-dot\PreviewDot\PreviewControl.cs:line 81

Log:
```

**Comment by laingsimon** [comment]
Could be related to: https://stackoverflow.com/questions/22708150/a-generic-error-occurred-in-gdi-at-system-drawing-image-save

**Comment by laingsimon** [comment]
Appears to be a permission related issue, process has no permission to save to user's temp directory.

e.g. `C:\Users\Simon\AppData\Local\Temp\9d1f43a5-d1f4-4ad6-aa58-362f7cfc334e.png`

The prevhost.exe process runs as the current user, so should be able to write to this path.

**Comment by laingsimon** [comment]
May require this change as part of installation:

```
HKEY_CLASSES_ROOT
   CLSID
      {YOUR HANDLER'S CLSID}
         DisableLowILProcessIsolation [DWORD] = 1
```
From: https://docs.microsoft.com/en-us/windows/desktop/shell/preview-handlers

**Comment by laingsimon** [comment]
Resolved by setting DisableLowILProcessIsolation as part of installation
